"""docs/reports/validation.md from validation/cases/*/case.json (`uv run python -m pipeline.validation report`)."""

from __future__ import annotations

import json

from ..paths import REPO
from .build import TOLERANCE_K, VALIDATION

REPORT = REPO / "docs" / "reports" / "validation.md"
CH = ("X", "Y", "Z", "S")

HEADER = """# Validation set: calibrated observations as ground truth for the renderer

*Generated by `uv run python -m pipeline.validation report` from `validation/cases/*/case.json`; the cases themselves
are built by `uv run python -m pipeline.validation build` (code: `pipeline/src/pipeline/validation/`).*

The question each case answers is *"is this what you would actually see?"*: for a real, calibrated image of a planet,
moon or ring system, the renderer must reproduce the **absolute radiance** in a few well-defined regions of the
picture, within tolerances that come from the data's own uncertainties.

## 1. What the renderer must output

**Quantity.** The HDR buffer in absolute **XYZS radiance**, before the eye model: X, Y, Z in cd/m² (K_m = 683.002
lm/W, CIE 1931 2° observer), S in scotopic cd/m² (K'_m = 1700.06 lm/W, CIE 1951), i.e. the renderer's `rgba32float`
XYZS luminance target. No exposure, glare/PSF, adaptation or tone mapping. The solar spectrum and observers are those
of `light.json` (TSIS-1 HSRS, CIE tables), so a Lambertian white disk at normal incidence, 1 AU from the Sun, has
Y = E_Y/π with E_Y = the Y of `light.json`'s `irradianceXYZS_1AU`.

**View.** Each case's `view` is explicit and complete; the harness must **not** recompute it from the app's ephemeris
(the epochs lie outside the app's time window, except the Himawari case). It maps 1:1 onto the renderer's types
(`app/src/render/scene.ts`):

| case.json | SceneSnapshot |
|---|---|
| `view.camera.orient` (row-major, camera→ICRF, columns right, up, back) | `camera.orient` |
| `view.camera.fovY`, `width`, `height` | `camera.fovY`, `width`, `height` |
| `view.bodies[i].pos` (camera-relative, km, ICRF, light-time corrected) | `bodies[i].pos` |
| `view.bodies[i].toSun`, `orient` (body-fixed→ICRF, row-major), `radii` | `bodies[i].toSun`, `orient`, `radii` |
| `view.bodies[i].rings` | attach the planet's `rings.json` system |
| `view.sun.pos` | `sun.pos` |
| `view.et` | `et` |

Everything photometric comes from the app's own data, exactly as in normal rendering: `photometry.json` (albedo,
phase function, spatial model, ROLO), surface maps, `rings.json`, `atmospheres.json`, at the reality level being
tested (the tolerances assume the most complete level that the data admit).
Pixel (x, y) with y down has the ray right·(x+½−W/2)s + up·(H/2−y−½)s − back, s = `pixelPitchRad` = 2 tan(fovY/2)/H.
The reference values are **area averages** over each pixel, so the harness should supersample (≥ 4 × 4 per pixel);
ROIs never contain pixels that straddle a limb, terminator, ring edge or shadow edge (§3.5).

**Interface** (types in `app/src/data/schema.ts`: `ValidationCase`, `ValidationRoi`, `ValidationRatio`):

```ts
// Render the case's view into the HDR target (no eye model), at view.camera.width × height.
renderValidationView(c: ValidationCase, opts?: { samplesPerPixel?: number; reality?: RealityLevel }): Promise<void>;
// Mean, standard deviation and pixel count of the HDR XYZS buffer over [x0, x1) × [y0, y1).
readHdrRegion(rect: [x0: number, y0: number, x1: number, y1: number]):
    Promise<{ mean: [X, Y, Z, S]; std: [X, Y, Z, S]; n: number }>;
// Optional, for pixel-by-pixel residual maps against reference.bin (I/F per band, same grid):
readHdr(): Promise<Float32Array>;   // width × height × 4 (X, Y, Z, S)
```

**Pass/fail**, per ROI and channel c:

```
value ROI:        |mean_c − expected.XYZS[c]| ≤ expected.tolerance[c]      (tolerance = 2σ)
upper-limit ROI:  mean_c ≤ expected.upperLimitXYZS[c]
ratio:            |mean_c(numerator rect) / mean_c(denominator rect) − ratioXYZS[c]| ≤ tolerance[c]
'none' ROI:       not compared (no valid data or no expectation)
```

A failing ROI is a finding about the app's data or the renderer, to be reported with the ROI's `geometry` (incidence,
emission, phase, latitude/longitude or ring radius), which says which part of the photometric model it probes.
`appDataPreview` (disk-integrated ROIs) evaluates the app's `photometry.json` disk brightness at the case's phase
angle *without* rendering: it tells in advance whether a disagreement is in the data or in the renderer.

## 2. Geometry

* **Observer → target**: JPL Horizons vector tables (VEC_CORR = 'LT', ICRF) from the missions' reconstructed
  trajectories (Cassini −82, Voyager 2 −32, New Horizons −98, EPOXI −140), one query per image mid-time, cached in
  `data/raw/validation/horizons/` with the query in the download ledger.
* **Orientation, radii, Sun**: NAIF pck00011 (IAU rotation models, at t − light time) and de442s; for the Earth
  (Himawari) the high-precision ITRF93 PCK.
* **Pointing and roll are fitted to the image** (the C-kernels are too large to fetch for a few frames): a model
  image (Lambert ellipsoid, rings as single-scattering slabs with the app's measured τ profile, sky offset; amplitudes
  by linear least squares) is matched on a 2× pyramid (FFT translation search every 3° of roll, then Nelder–Mead).
  **Parity** (whether the archive's display order is mirrored): from the image fit where it decides (Saturn's rings);
  otherwise from independent evidence — the LORRI header WCS (sign of det CD); for Voyager 2 a reference frame of
  the same camera with Saturn's rings and four moons (a mirrored solution puts the moons where there is no light);
  for EPOXI the Moon beside the Earth. **Roll**: free for Saturn and the EPOXI Earth (set by the Moon's observed
  position); the LORRI WCS roll for LORRI (a sphere at low phase hardly constrains it: the free fit was 21° off for
  Pluto); for the Voyager sequences the frames' common (mean) roll, their spread being the roll uncertainty.
* **Independent checks** (`pointingChecks`): the fitted boresight against the centre of OPUS's RA/Dec footprint
  (mission C-kernel pointing), and for LORRI the header WCS pixel of the target against the fitted centre; the
  stellar-aberration shift (Horizons LT+S − LT) is added first because the archives' pointing is apparent.
* **Registration uncertainty** δ = max(0.5 view pixel, 3σ of the fitted centre) ⊕ (roll uncertainty × the ROI's
  distance from the target centre), propagated as δ × |∇(ROI mean)|.
* All band images of a case are resampled (area average) onto the reference image's view with their own fits.

## 3. Photometry and uncertainties

1. **I/F** as the archives define it (CISSCAL for Cassini, FICOR77 for Voyager, the SOC recipe with RSOLAR for
   LORRI, MULT2IOF for EPOXI, π L d²/E_band for Himawari): the solar-weighted band average of the reflectance.
2. **Band radiance** L_b = I/F · Ē_b / (π d²), Ē_b the TSIS-1 HSRS irradiance averaged over the band response
   (photon- or energy-weighted as the response is tabulated), d the Sun distance in AU.
3. **XYZS** exactly as the app models surface colour (`surf_color.py`): r(λ) = p̃(λ)·ρ(λ), ρ_b = I/F_b / p̃_b, ρ
   interpolated linearly between the bands' effective wavelengths and held flat beyond; p̃ = the body's
   disk-integrated spectrum (grey for ring ROIs). Colour label `derived` only under surf_color's Nyquist criterion,
   else `estimated`.
4. **1σ budget** per channel: calibration (instrument documentation, fully correlated between bands), noise (ROI
   standard deviation / √n, which also counts the scene's texture inside the ROI), registration, and the spectral
   model (linear vs monotone-cubic interpolation of ρ; for one band, p̃-shaped vs grey spectrum).
5. **ROIs** are square windows (plus a 1-pixel margin) whose every 4 × 4 sub-sample lies in one class: lit surface
   of the target with the kind's angle limits, lit ring face within a radius band, or empty sky. Kinds: disk-centre
   (smallest emission), limb (emission ≥ 60°, 70° for the Earth; brightest), terminator (incidence 65-88°),
   ring (radius band), disk-integrated (rectangle around the whole disk; sums all its light, immune to PSF blur;
   the local sky level in a 5-pixel frame around it, i.e. the camera's scattered light, is subtracted),
   sky-near / sky-far (upper limits).
6. **Tolerance** = """ + f"{TOLERANCE_K:g}" + """σ of the combined budget, two-sided.

"""


def _f(v, nd=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        if v != 0 and (abs(v) >= 1e4 or abs(v) < 1e-3):
            return f"{v:.{nd}e}"
        return f"{v:.{nd}g}" if abs(v) < 1 else f"{v:.{max(nd, 4)}g}"
    return str(v)


def _geo(g: dict) -> str:
    parts = []
    for k, lab in (("incidenceDeg", "i"), ("emissionDeg", "e"), ("phaseDeg", "α")):
        if k in g:
            parts.append(f"{lab} {g[k]['mean']:.1f}°")
    if "ringRadiusKm" in g:
        parts.append(f"r {g['ringRadiusKm']['mean'] / 1000:.1f} Mm")
    elif "latitudeDeg" in g:
        parts.append(f"lat {g['latitudeDeg']['mean']:.1f}°")
    return ", ".join(parts)


def case_section(c: dict) -> str:
    v = c["view"]
    b0 = v["bodies"][0]
    obs = c["observation"]
    L = [f"### {c['title']}  (`{c['id']}`)", "", c["summary"], "",
         f"![{c['id']}](../../validation/cases/{c['id']}/preview.png)", "",
         f"* **Observer / instrument:** {obs['observer']} "
         + (f"(Horizons {obs['observerHorizonsId']})" if obs['observerHorizonsId'].startswith("@")
            else f"{obs['observerHorizonsId']}") + f", {obs['instrument']}.",
         f"* **Epoch (reference image):** {v['epochUtc']} UTC (ET {v['et']:.3f}).",
         f"* **Geometry:** range {b0['rangeKm']:.6g} km, phase {b0['phaseDeg']:.2f}°, Sun distance "
         f"{b0['sunDistanceAu']:.5f} AU; sub-observer {b0['subObserver']['latDeg']:.2f}°, "
         f"{b0['subObserver']['eastLonDeg']:.2f}°E; sub-solar {b0['subSolar']['latDeg']:.2f}°, "
         f"{b0['subSolar']['eastLonDeg']:.2f}°E (planetocentric).",
         f"* **View:** {v['camera']['width']} × {v['camera']['height']} px, pixel "
         f"{v['camera']['pixelPitchRad'] * 1e6:.3f} "
         f"µrad (native {obs['pixel']['nativePitchRad'] * 1e6:.3f} µrad × {obs['pixel']['binning']}), mirrored archive "
         f"order: {obs['pixel'].get('mirroredDisplayOrder')}.",
         f"* **Calibration (1σ):** {', '.join(f'{s:.0%}' for s in obs['calibration']['sigmaRel1'])} — "
         f"{obs['calibration']['note']}", ""]
    if len(v["bodies"]) > 1:
        for b in v["bodies"][1:]:
            L.insert(-1, f"* **Also in view:** {b['name']} (range {b['rangeKm']:.6g} km, phase {b['phaseDeg']:.2f}°).")
    L += ["| image | filter | mid-time (UTC) | fit: centre (px), roll | residual rms (I/F) | other parity rss / rss | "
          "registration δ (px) | pointing check |", "|---|---|---|---|---|---|---|---|"]
    for im in obs["images"]:
        ft = im.get("fit")
        chk = "; ".join(f"{p['offsetNativePx']} native px" + (" (inside footprint)" if p.get("insideFootprint") else
                                                               (" (outside footprint)" if "insideFootprint" in p else
                                                                " (WCS)"))
                        for p in im.get("pointingChecks", [])) or "—"
        if ft:
            fit = f"({ft['targetCentrePx'][0]:.2f}, {ft['targetCentrePx'][1]:.2f}), {ft['rollDeg']:.3f}°"
            ratio = (f"{ft['rssOtherParity'] / ft['rss']:.2f}" if ft.get("rssOtherParity") else "—")
            resid = _f(ft["residualRmsIoverF"])
        else:
            fit, ratio, resid = "navigated (no fit)", "—", "—"
        L.append(f"| {im['product']} | {im['band']} | {im['utcMid']} | {fit} | {resid} | {ratio} | "
                 f"{im['registrationSigmaPx']:.3g} | {chk} |")
    L += ["", "| ROI | kind | rect | geometry | I/F per band | expected Y (cd/m²) ± 2σ | X, Z, S | label |",
          "|---|---|---|---|---|---|---|---|"]
    for r in c["rois"]:
        e = r["expected"]
        iof = ", ".join(_f(b["iof"]["mean"]) for b in r["bands"])
        if e["type"] == "value":
            y = f"{_f(e['XYZS'][1])} ± {_f(e['tolerance'][1])}"
            xzs = ", ".join(_f(e["XYZS"][k]) for k in (0, 2, 3))
        elif e["type"] == "upper-limit":
            y = f"≤ {_f(e['upperLimitXYZS'][1])}"
            xzs = "≤ " + ", ".join(_f(e["upperLimitXYZS"][k]) for k in (0, 2, 3))
        else:
            y, xzs = "—", "—"
        extra = f" (cloud offset {r['cloudTimeOffsetH']:+.1f} h)" if "cloudTimeOffsetH" in r else ""
        L.append(f"| {r['id']}{extra} | {r['kind']} | {r['rect']} | {_geo(r['geometry'])} | {iof} | {y} | {xzs} | "
                 f"{e.get('label', '—')} |")
    prev = [r for r in c["rois"] if r.get("appDataPreview")]
    if prev:
        L += ["", "App data preview (informational, no rendering: `photometry.json` disk brightness at this "
                  "phase):", ""]
        for r in prev:
            p = r["appDataPreview"]
            if "XYZS" in p:
                dev = p.get("deviationInSigma")
                L.append(f"* {r['id']}: app Y = {_f(p['XYZS'][1])} cd/m², ratio to observed "
                         f"{', '.join(f'{x:.3f}' for x in p.get('ratioToExpected', []))} (X, Y, Z, S)"
                         + (f", i.e. {', '.join(f'{d:+.1f}' for d in dev)} σ" if dev else "")
                         + f"; Φ({p['phaseDeg']:.1f}°) = {p['phi']:.3f} ({p['labels']['phaseFunction']}).")
            else:
                L.append(f"* {r['id']}: {p['note']}")
    for q in c.get("ratios", []):
        L += ["", f"Calibration-free ratio {q['numerator']} / {q['denominator']}: XYZS "
              f"{', '.join(_f(x) for x in q['ratioXYZS'])} ± {', '.join(_f(2 * s) for s in q['sigma'])} (2σ); per band "
              + ", ".join(f"{b['filter']} {b['ratio']:.4f}" for b in q["bands"]) + "."]
    if c.get("notes"):
        L += ["", "Notes:", ""] + [f"* {n}" for n in c["notes"]]
    return "\n".join(L) + "\n"


def summary_table(cases: list[dict]) -> str:
    L = ["| case | target | instrument | epoch (UTC) | bands | ROIs | calibration 1σ | pointing check (native px) |",
         "|---|---|---|---|---|---|---|---|"]
    for c in cases:
        o = c["observation"]
        chk = [p["offsetNativePx"] for im in o["images"] for p in im.get("pointingChecks", [])]
        L.append(f"| `{c['id']}` | {o['target']['name']} | {o['instrument']} | {c['view']['epochUtc'][:19]} | "
                 f"{len(c['reference']['bands'])} | {len(c['rois'])} | "
                 f"{max(o['calibration']['sigmaRel1']):.0%} | {', '.join(f'{x:g}' for x in chk) or '—'} |")
    return "\n".join(L) + "\n"


def _du(path) -> float:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / 1e6


def findings(cases: list[dict]) -> str:
    """§5: checks of the set itself, computed from the cases, then the fixed text of §6."""
    from ..paths import RAW
    L = ["## 5. Checks of the set itself\n",
         "**Image parity and roll** (the archive's display order relative to a right-handed camera):\n"]
    for c in cases:
        px = c["observation"]["pixel"]
        L.append(f"* `{c['id']}`: {'mirrored' if px.get('mirroredDisplayOrder') else 'direct'} — "
                 f"{px.get('parityDecision') or 'navigated grid (no parity question)'}.")
        rn = [im["fit"].get("rollNote") for im in c["observation"]["images"] if im.get("fit")]
        if rn and rn[0]:
            L.append(f"  Roll: {rn[0]}.")
    L += ["", "**Fitted pointing against the missions' own pointing** (`pointingChecks`, native pixels):", ""]
    for c in cases:
        items = []
        for im in c["observation"]["images"]:
            for p in im.get("pointingChecks", []):
                tag = "WCS target" if "wcsPixel" in p else "OPUS boresight"
                extra = (f", roll {p['rollDifferenceDeg']:+.2f}° from the WCS" if "rollDifferenceDeg" in p
                         else "")
                items.append(f"{im['product']} {tag} {p['offsetNativePx']:g}{extra}")
        if items:
            L.append(f"* `{c['id']}`: " + "; ".join(items) + ".")
    L += ["", "These offsets are the missions' attitude-knowledge errors plus ours; the fits themselves are tied to "
          "the target's own limb and terminator, which is what the renderer comparison needs. The three Saturn "
          "frames agree with one another to 0.5 binned pixel.", ""]
    L += ["**App data preview** (disk-integrated ROIs; `photometry.json` alone, no rendering):", ""]
    for c in cases:
        for r in c["rois"]:
            pv = r.get("appDataPreview")
            if not pv:
                continue
            body = next((b for b in c["view"]["bodies"] if b["naifId"] == r.get("target")), None)
            where = (f" (phase {body['phaseDeg']:.1f}°, sub-observer {body['subObserver']['latDeg']:+.1f}° "
                     f"{body['subObserver']['eastLonDeg'] % 360:.1f}° E)" if body else "")
            if "XYZS" in pv and "ratioToExpected" in pv:
                L.append(f"* `{c['id']}` {r['id']}{where}: app/observed Y = {pv['ratioToExpected'][1]:.3f} "
                         f"({pv['deviationInSigma'][1]:+.1f} σ), X {pv['ratioToExpected'][0]:.3f}, "
                         f"Z {pv['ratioToExpected'][2]:.3f}; phase function {pv['labels']['phaseFunction']}.")
            elif "XYZS" in pv:
                L.append(f"* `{c['id']}` {r['id']}: app Y = {pv['XYZS'][1]:.4g} cd/m² (no observed value for this "
                         "ROI).")
            else:
                L.append(f"* `{c['id']}` {r['id']}: {pv['note']}.")
    ledger = json.loads((RAW / "_downloads.json").read_text())
    fetched = sum(v.get("bytes", 0) for k, v in ledger.items() if k.startswith("validation/")) / 1e6
    L += ["", f"**Sizes:** `validation/` {_du(VALIDATION):.1f} MB (committed); downloaded inputs {fetched:.1f} MB "
          f"(download ledger), git-ignored in `data/raw/validation/` ({_du(RAW / 'validation'):.1f} MB present now: "
          "`python -m pipeline.validation clean` deletes the images after a build; `build` fetches them again, and "
          "the pointing-fit cache is keyed by each image's sha256, so a changed archive file is refitted).", "",
          "**Unit tests** (`pipeline/tests/test_validation.py`): the camera puts the target at the requested pixel "
          "with the pole up; ray casting reproduces a sphere's projected area to 1 % and face-on emission; ring "
          "classes and radii; the pointing fit recovers a synthetic pose to 0.15 px and 2°; grey closure (I/F = 1 "
          "in every band gives exactly the XYZS of sunlight / π d²); band radiance definition; PDS3 label parsing; the "
          "Himawari grid mapping round trip; the companion parity test; and every committed case.json (orthonormal "
          "camera and body matrices, fovY/pitch consistency, reference.bin size, ROI rectangles inside the view, "
          "tolerance = 2σ, fitted target centre = the view's projection of the target).", ""]
    return "\n".join(L) + "\n"


def write(extra_sections: str = "") -> None:
    cases = [json.loads(p.read_text()) for p in sorted((VALIDATION / "cases").glob("*/case.json"))]
    parts = [HEADER, "## 4. The cases\n\n", summary_table(cases), "\n",
             "Sizes: `validation/` holds only case.json, reference.bin (float32 I/F on the view grid) and "
             "preview.png per case; the downloaded images are fetched into `data/raw/validation/` (git-ignored) "
             "and may be deleted after the build (`clean`).\n\n"]
    for c in cases:
        parts.append(case_section(c) + "\n")
    parts.append(findings(cases))
    parts.append(extra_sections)
    REPORT.write_text("".join(parts))


FINDINGS = """## 6. Limitations and open issues

1. **Pointing is fitted, not taken from C-kernels.** The missions' attitude kernels are hundreds of MB per year. The
   fitted camera is tied to the target itself (limb, terminator, rings), which is what a radiance comparison needs;
   the mission pointing serves as a check (§5) and, where the image cannot decide, for the parity (Voyager: a
   Saturn frame with four moons; LORRI: the header WCS, which also gives the roll).
2. **Scene changes with time are not in the tolerance.** Earth's clouds (only the Himawari ROIs within ±1 h of the
   VIIRS overpass see the app's clouds; `cloudTimeOffsetH`), Neptune's and Jupiter's cloud features, Io's volcanic
   deposits, seasonal changes since the observation. The ROI standard deviation enters the noise term, which makes
   textured ROIs looser but does not cover a systematically different scene.
3. **Single-band cases (LORRI)** give XYZS only through the body's disk-integrated spectral shape ('estimated');
   regional colour differences (Pluto's red Cthulhu and white Sputnik, Io's sulphur colours) can exceed the
   grey-versus-shape spectral term. The band radiance itself is 'derived' and is the sharper quantity.
4. **Instrument responses:** the Voyager filter curves are the pre-launch curves digitized from Smith et al. (1977)
   and are generic to both spacecraft; the HRI-VIS 350, 550 and 650 nm filters have red leaks; the LORRI response is
   the SVO copy of the archive's launch calibration.
5. **LORRI RSOLAR for 2007:** the Jupiter-encounter archive carries the pre-flight keyword (13 % higher than the
   2016 in-flight value used here, per Weaver et al. 2020's stability finding).
6. **Not included:** Mars (no calibrated full-disk image found within reach: the Emirates Mars Mission archive is
   behind a JavaScript check, the ESA PSA was not tried); Mercury (the MESSENGER MDIS CDR directory tried at the PDS
   Geosciences Node answered "webpage unavailable"; not pursued further); a high-resolution Moon (the Cassini 1999
   lunar images in the calibrated holdings have I/F ~25× too high, consistent with CISSCAL's Jupiter
   solar-distance option, validation-cassini-iss.md); Titan (its haze optics are 'unknown' in atmospheres.json);
   Venus.
7. **Himawari:** one segment of ten (the equatorial swath); no disk-integrated ROI from this scene (the app's Earth
   albedo itself comes from the 2025-03-20 Himawari scene).
8. **Sky ROIs** are upper limits only: every camera's scattered light and zero level are in them.
9. **Sampling:** the reference is an area average per pixel; a renderer sampling pixel centres only will differ at
   ROI edges by up to the within-ROI gradient × ½ pixel, which the registration term does not include for it.
10. **The app data preview's misses (§5) are findings about photometry.json, not about a renderer.** Where it is
    off by more than 2σ, its own methods say why it can be: the **Moon** entry is the ROLO model, fitted to
    Earth-based photometry of the near side, while EPOXI saw the far side (sub-observer longitude ~175° E), which
    has a larger highland fraction and is brighter; the **Galilean** entries use Mayorga et al.'s (2020)
    longitude-averaged GRN phase curve (rotational variations, their Table 4, are not represented; the fit has no
    data between 30° and 60° phase, where Io's 35.6° and Callisto's 46.5° lie) at every wavelength, with LORRI's broad band compared
    through the body's single spectral shape. The size of each effect here is not quantified; the next step is the
    rotational terms of Mayorga et al. Table 4 at the LORRI sub-observer longitudes listed in §5. A renderer
    comparison is unaffected: it is judged against the observed values, not against this preview.
"""
