"""docs/reports/validation.md from validation/cases/*/case.json (`uv run python -m pipeline.validation report`)."""

from __future__ import annotations

import json
import math

from ..paths import REPO
from .build import TOLERANCE_K, VALIDATION

REPORT = REPO / "docs" / "reports" / "validation.md"
CH = ("X", "Y", "Z", "S")

HEADER = """# Validation set: calibrated observations as ground truth for the renderer

*Generated by `uv run python -m pipeline.validation report` from `validation/cases/*/case.json`; the cases themselves
are built by `uv run python -m pipeline.validation build` (code: `pipeline/src/pipeline/validation/`).*

The question each case answers is *"is this what you would actually see?"*: for a real, calibrated image of a planet,
moon or ring system, the renderer must reproduce the **absolute radiance** in a few well-defined regions of the
picture, within tolerances that come from the data's own uncertainties.

**Method: the cases test the model; they never select it.** The app's data (albedos, phase curves, spatial laws,
calibrations) are chosen by the sources' own merits and by their coverage of the geometry: which body, phase angles,
latitudes, season and wavelengths they measure, and how directly. How a choice scores on these cases plays no part.
- **Competing published laws:** when two exist, or a published law and an approximation of it, the better-supported
  one is used on that evidence. For example, Saturn uses the native Barkstrom law of Dones et al. (1993),
  rather than its Minnaert approximation. The terminator comparison also includes ringshine the app omits (§7).
- **Independence must be stated:** an independent comparison must exclude sources that include the tested frame
  (e.g. Belgacem's regional Europa fits are excluded). Pluto's map and law share flyby inputs with its case;
  those rows do not provide an independent check (§7).
- **No correction factors from the cases:** a factor derived from a case (e.g. the Galilean LORRI offset) is
  documented as a bound, not applied.

A choice made after seeing a case must be justifiable without it; otherwise the test leaks into the model and the
case no longer measures anything.

## 1. What the renderer must output

**Quantity.** The HDR buffer in absolute **XYZS radiance**, before the eye model: X, Y, Z in cd/m² (K_m = 683.002
lm/W, CIE 1931 2° observer), S in scotopic cd/m² (K'_m = 1700.06 lm/W, CIE 1951), i.e. the renderer's `rgba32float`
XYZS luminance target. No exposure, glare/PSF, adaptation or tone mapping. The solar spectrum and observers are those
of `light.json` (TSIS-1 HSRS, CIE tables), so a Lambertian white disk at normal incidence, 1 AU from the Sun, has
Y = E_Y/π with E_Y = the Y of `light.json`'s `irradianceXYZS_1AU`.

**View.** Each case's `view` is explicit and complete; the harness must **not** recompute it from the app's ephemeris
(the epochs lie outside the app's time window, except the Himawari case). It maps 1:1 onto the renderer's types
(`app/src/render/scene.ts`):

| case.json | SceneSnapshot |
|---|---|
| `view.camera.orient` (row-major, camera→ICRF, columns right, up, back) | `camera.orient` |
| `view.camera.fovY`, `width`, `height` | `camera.fovY`, `width`, `height` |
| `view.bodies[i].pos` (camera-relative, km, ICRF, light-time corrected) | `bodies[i].pos` |
| `view.bodies[i].toSun`, `orient` (body-fixed→ICRF, row-major), `radii` | `bodies[i].toSun`, `orient`, `radii` |
| `view.bodies[i].rings` | attach the planet's `rings.json` system |
| `view.sun.pos` | `sun.pos` |
| `view.et` | `et` |

Everything photometric comes from the app's own data, exactly as in normal rendering: `photometry.json` (albedo,
phase function, spatial model, ROLO), surface maps, `rings.json`, `atmospheres.json`, at the reality level being
tested (the tolerances assume the most complete level that the data admit).
Pixel (x, y) with y down has the ray right·(x+½−W/2)s + up·(H/2−y−½)s − back, s = `pixelPitchRad` = 2 tan(fovY/2)/H.
The reference values are **area averages** over each pixel, so the harness should supersample; the recorded grid
and, when supplied, the sampling sweep below describe the numerical evidence for that run.
Local body and ring ROIs exclude pixels that straddle a limb, terminator, ring edge or shadow edge (§3.5).
Disk-integrated rectangles deliberately include the entire disk.

**Interface** (types in `app/src/data/schema.ts`: `ValidationCase`, `ValidationRoi`, `ValidationRatio`), implemented
in the app (`cd app && npm run validate`; app/e2e/README.md "Validation against calibrated images"; results in
`app/shots/validation/`, and §7 below):

```ts
// app/src/validation/runner.ts: the case's view as a SceneSnapshot with the app's data (geometry-only: every body
// placed and oriented as case.json says, so the epoch need not lie in the app's time window).
validationScene(c: ValidationCase, data, opts?: { ss?: number; reality?: 'strict' | 'best' | 'complete' }): ValidationScene;
// validation.html: render it (ss × ss samples per pixel), settle, read and compare every ROI and ratio.
window.__validation.run(c: ValidationCase, opts?): Promise<RunResult>;
// app/src/render/renderer.ts (marked hook; render/hdrReadback.ts): the HDR XYZS target of the last frame, before the
// eye model, in cd/m² (S in scotopic cd/m²): mean, standard deviation and count over [x0, x1) × [y0, y1).
renderer.readHdrRegion(rect: [x0: number, y0: number, x1: number, y1: number]):
    Promise<{ mean: [X, Y, Z, S]; std: [X, Y, Z, S]; n: number }>;
// The whole target, for residual maps against reference.bin (I/F per band, same grid):
renderer.readHdr(): Promise<{ width: number; height: number; data: Float32Array }>;   // width × height × 4
```

**Pass/fail**, per ROI and channel c:

```
value ROI:        |mean_c − expected.XYZS[c]| ≤ expected.tolerance[c]      (tolerance = 2σ)
upper-limit ROI:  mean_c ≤ expected.upperLimitXYZS[c]
ratio:            |mean_c(numerator rect) / mean_c(denominator rect) − ratioXYZS[c]| ≤ tolerance[c]
'none' ROI:       not compared (no valid data or no expectation)
```

A failing ROI is a finding about the app's data or the renderer, to be reported with the ROI's `geometry` (incidence,
emission, phase, latitude/longitude or ring radius), which says which part of the photometric model it probes.
`appDataPreview` (disk-integrated ROIs) evaluates the app's `photometry.json` disk brightness at the case's phase
angle *without* rendering: it tells in advance whether a disagreement is in the data or in the renderer.

## 2. Geometry

* **Observer → target**: JPL Horizons vector tables (VEC_CORR = 'LT', ICRF) from the missions' reconstructed
  trajectories (Cassini −82, Voyager 2 −32, New Horizons −98, EPOXI −140), one query per image mid-time, cached in
  `data/raw/validation/horizons/` with the query in the download ledger.
* **Orientation, radii, Sun**: NAIF pck00011 (IAU rotation models, at t − light time) and de442s; for the Earth
  (Himawari) the high-precision ITRF93 PCK.
* **Pointing and roll are fitted to the image** (the C-kernels are too large to fetch for a few frames): a model
  image (Lambert ellipsoid, rings as single-scattering slabs with the app's measured τ profile, sky offset; amplitudes
  by linear least squares) is matched on a 2× pyramid (FFT translation search every 3° of roll, then Nelder–Mead).
  **Parity** (whether the archive's display order is mirrored): from the image fit where it decides (Saturn's rings);
  otherwise from independent evidence — the LORRI header WCS (sign of det CD); for Voyager 2 a reference frame of
  the same camera with Saturn's rings and four moons (a mirrored solution puts the moons where there is no light);
  for EPOXI the Moon beside the Earth. **Roll**: free for Saturn and the EPOXI Earth (set by the Moon's observed
  position); the LORRI WCS roll for LORRI (a sphere at low phase hardly constrains it: the free fit was 21° off for
  Pluto); for the Voyager sequences the frames' common (mean) roll, their spread being the roll uncertainty.
* **Independent checks** (`pointingChecks`): the fitted boresight against the centre of OPUS's RA/Dec footprint
  (mission C-kernel pointing), and for LORRI the header WCS pixel of the target against the fitted centre; the
  stellar-aberration shift (Horizons LT+S − LT) is added first because the archives' pointing is apparent.
* **Registration uncertainty** δ = max(0.5 view pixel, 3σ of the fitted centre) ⊕ (roll uncertainty × the ROI's
  distance from the target centre), propagated as δ × |∇(ROI mean)|.
* All band images of a case are resampled (area average) onto the reference image's view with their own fits.

## 3. Photometry and uncertainties

1. **I/F** as the archives define it (CISSCAL for Cassini, FICOR77 for Voyager, the SOC recipe with RSOLAR for
   LORRI, MULT2IOF for EPOXI, π L d²/E_band for Himawari): the solar-weighted band average of the reflectance.
2. **Band radiance** L_b = I/F · Ē_b / (π d²), Ē_b the TSIS-1 HSRS irradiance averaged over the band response
   (photon- or energy-weighted as the response is tabulated), d the Sun distance in AU.
3. **XYZS** exactly as the app models surface colour (`surf_color.py`): r(λ) = p̃(λ)·ρ(λ), ρ_b = I/F_b / p̃_b, ρ
   interpolated linearly between the bands' effective wavelengths and held flat beyond; p̃ = the body's
   disk-integrated spectrum (grey for ring ROIs). Colour label `derived` only under surf_color's Nyquist criterion,
   else `estimated`.
4. **1σ budget** per channel: calibration (instrument documentation, fully correlated between bands), noise (ROI
   standard deviation / √n, which also counts the scene's texture inside the ROI), registration, and the spectral
   model (linear vs monotone-cubic interpolation of ρ; for one band, p̃-shaped vs grey spectrum).
5. **ROIs** are square windows (plus a 1-pixel margin) whose every 4 × 4 sub-sample lies in one class: lit surface
   of the target with the kind's angle limits, lit ring face within a radius band, or empty sky. Kinds: disk-centre
   (smallest emission), limb (emission ≥ 60°, 70° for the Earth; brightest), terminator (incidence 65-88°),
   ring (radius band), disk-integrated (rectangle around the whole disk; sums all its light, immune to PSF blur;
   the local sky level in a 5-pixel frame around it, i.e. the camera's scattered light, is subtracted),
   sky-near / sky-far (upper limits).
6. **Tolerance** = """ + f"{TOLERANCE_K:g}" + """σ of the combined budget, two-sided.

"""


def _f(v, nd=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        if v != 0 and (abs(v) >= 1e4 or abs(v) < 1e-3):
            return f"{v:.{nd}e}"
        return f"{v:.{nd}g}" if abs(v) < 1 else f"{v:.{max(nd, 4)}g}"
    return str(v)


def _geo(g: dict) -> str:
    parts = []
    for k, lab in (("incidenceDeg", "i"), ("emissionDeg", "e"), ("phaseDeg", "α")):
        if k in g:
            parts.append(f"{lab} {g[k]['mean']:.1f}°")
    if "ringRadiusKm" in g:
        parts.append(f"r {g['ringRadiusKm']['mean'] / 1000:.1f} Mm")
    elif "latitudeDeg" in g:
        parts.append(f"lat {g['latitudeDeg']['mean']:.1f}°")
    return ", ".join(parts)


def case_section(c: dict) -> str:
    v = c["view"]
    b0 = v["bodies"][0]
    obs = c["observation"]
    L = [f"### {c['title']}  (`{c['id']}`)", "", c["summary"], "",
         f"![{c['id']}](../../validation/cases/{c['id']}/preview.png)", "",
         f"* **Observer / instrument:** {obs['observer']} "
         + (f"(Horizons {obs['observerHorizonsId']})" if obs['observerHorizonsId'].startswith("@")
            else f"{obs['observerHorizonsId']}") + f", {obs['instrument']}.",
         f"* **Epoch (reference image):** {v['epochUtc']} UTC (ET {v['et']:.3f}).",
         f"* **Geometry:** range {b0['rangeKm']:.6g} km, phase {b0['phaseDeg']:.2f}°, Sun distance "
         f"{b0['sunDistanceAu']:.5f} AU; sub-observer {b0['subObserver']['latDeg']:.2f}°, "
         f"{b0['subObserver']['eastLonDeg']:.2f}°E; sub-solar {b0['subSolar']['latDeg']:.2f}°, "
         f"{b0['subSolar']['eastLonDeg']:.2f}°E (planetocentric).",
         f"* **View:** {v['camera']['width']} × {v['camera']['height']} px, pixel "
         f"{v['camera']['pixelPitchRad'] * 1e6:.3f} "
         f"µrad (native {obs['pixel']['nativePitchRad'] * 1e6:.3f} µrad × {obs['pixel']['binning']}), mirrored archive "
         f"order: {obs['pixel'].get('mirroredDisplayOrder')}.",
         f"* **Calibration (1σ):** {', '.join(f'{s:.0%}' for s in obs['calibration']['sigmaRel1'])} — "
         f"{obs['calibration']['note']}", ""]
    if len(v["bodies"]) > 1:
        for b in v["bodies"][1:]:
            L.insert(-1, f"* **Also in view:** {b['name']} (range {b['rangeKm']:.6g} km, phase {b['phaseDeg']:.2f}°).")
    L += ["| image | filter | mid-time (UTC) | fit: centre (px), roll | residual rms (I/F) | other parity rss / rss | "
          "registration δ (px) | pointing check |", "|---|---|---|---|---|---|---|---|"]
    for im in obs["images"]:
        ft = im.get("fit")
        chk = "; ".join(f"{p['offsetNativePx']} native px" + (" (inside footprint)" if p.get("insideFootprint") else
                                                               (" (outside footprint)" if "insideFootprint" in p else
                                                                " (WCS)"))
                        for p in im.get("pointingChecks", [])) or "—"
        if ft:
            fit = f"({ft['targetCentrePx'][0]:.2f}, {ft['targetCentrePx'][1]:.2f}), {ft['rollDeg']:.3f}°"
            ratio = (f"{ft['rssOtherParity'] / ft['rss']:.2f}" if ft.get("rssOtherParity") else "—")
            resid = _f(ft["residualRmsIoverF"])
        else:
            fit, ratio, resid = "navigated (no fit)", "—", "—"
        L.append(f"| {im['product']} | {im['band']} | {im['utcMid']} | {fit} | {resid} | {ratio} | "
                 f"{im['registrationSigmaPx']:.3g} | {chk} |")
    L += ["", "| ROI | kind | rect | geometry | I/F per band | expected Y (cd/m²) ± 2σ | X, Z, S | label |",
          "|---|---|---|---|---|---|---|---|"]
    for r in c["rois"]:
        e = r["expected"]
        iof = ", ".join(_f(b["iof"]["mean"]) for b in r["bands"])
        if e["type"] == "value":
            y = f"{_f(e['XYZS'][1])} ± {_f(e['tolerance'][1])}"
            xzs = ", ".join(_f(e["XYZS"][k]) for k in (0, 2, 3))
        elif e["type"] == "upper-limit":
            y = f"≤ {_f(e['upperLimitXYZS'][1])}"
            xzs = "≤ " + ", ".join(_f(e["upperLimitXYZS"][k]) for k in (0, 2, 3))
        else:
            y, xzs = "—", "—"
        extra = f" (cloud offset {r['cloudTimeOffsetH']:+.1f} h)" if "cloudTimeOffsetH" in r else ""
        L.append(f"| {r['id']}{extra} | {r['kind']} | {r['rect']} | {_geo(r['geometry'])} | {iof} | {y} | {xzs} | "
                 f"{e.get('label', '—')} |")
    prev = [r for r in c["rois"] if r.get("appDataPreview")]
    if prev:
        L += ["", "App data preview (informational, no rendering: `photometry.json` disk brightness at this "
                  "phase):", ""]
        for r in prev:
            p = r["appDataPreview"]
            if "XYZS" in p:
                dev = p.get("deviationInSigma")
                L.append(f"* {r['id']}: app Y = {_f(p['XYZS'][1])} cd/m², ratio to observed "
                         f"{', '.join(f'{x:.3f}' for x in p.get('ratioToExpected', []))} (X, Y, Z, S)"
                         + (f", i.e. {', '.join(f'{d:+.1f}' for d in dev)} σ" if dev else "")
                         + f"; Φ({p['phaseDeg']:.1f}°) = {p['phi']:.3f} ({p['labels']['phaseFunction']}).")
            else:
                L.append(f"* {r['id']}: {p['note']}")
    for q in c.get("ratios", []):
        L += ["", f"Calibration-free ratio {q['numerator']} / {q['denominator']}: XYZS "
              f"{', '.join(_f(x) for x in q['ratioXYZS'])} ± {', '.join(_f(2 * s) for s in q['sigma'])} (2σ); per band "
              + ", ".join(f"{b['filter']} {b['ratio']:.4f}" for b in q["bands"]) + "."]
    if c.get("notes"):
        L += ["", "Notes:", ""] + [f"* {n}" for n in c["notes"]]
    return "\n".join(L) + "\n"


def summary_table(cases: list[dict]) -> str:
    L = ["| case | target | instrument | epoch (UTC) | bands | ROIs | calibration 1σ | pointing check (native px) |",
         "|---|---|---|---|---|---|---|---|"]
    for c in cases:
        o = c["observation"]
        chk = [p["offsetNativePx"] for im in o["images"] for p in im.get("pointingChecks", [])]
        L.append(f"| `{c['id']}` | {o['target']['name']} | {o['instrument']} | {c['view']['epochUtc'][:19]} | "
                 f"{len(c['reference']['bands'])} | {len(c['rois'])} | "
                 f"{max(o['calibration']['sigmaRel1']):.0%} | {', '.join(f'{x:g}' for x in chk) or '—'} |")
    return "\n".join(L) + "\n"


def _du(path) -> float:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / 1e6


def sizes_line(committed_mb: float, ledger: dict, present_mb: float) -> str:
    """§5's sizes: the committed cases, and the downloaded inputs as this machine's download ledger records them.
    A machine whose ledger has no entry under validation/ never fetched them (the cases were built elsewhere): the
    line says so instead of printing a total of zero."""
    fetched = [v.get("bytes", 0) for k, v in ledger.items() if k.startswith("validation/")]
    head = f"**Sizes:** `validation/` {committed_mb:.1f} MB (committed); "
    tail = ("`python -m pipeline.validation clean` deletes the images after a build; `build` fetches them again, and "
            "the pointing-fit cache is keyed by each image's sha256, so a changed archive file is refitted).")
    if not fetched:
        return (head + "the downloaded inputs are not on this machine (its download ledger has no entry under "
                f"`validation/`, and the git-ignored `data/raw/validation/` holds {present_mb:.1f} MB: " + tail)
    return (head + f"downloaded inputs {sum(fetched) / 1e6:.1f} MB (download ledger), git-ignored in "
            f"`data/raw/validation/` ({present_mb:.1f} MB present now: " + tail)


def findings(cases: list[dict]) -> str:
    """§5: checks of the set itself, computed from the cases, then the fixed text of §6."""
    from ..paths import RAW
    L = ["## 5. Checks of the set itself\n",
         "**Image parity and roll** (the archive's display order relative to a right-handed camera):\n"]
    for c in cases:
        px = c["observation"]["pixel"]
        L.append(f"* `{c['id']}`: {'mirrored' if px.get('mirroredDisplayOrder') else 'direct'} — "
                 f"{px.get('parityDecision') or 'navigated grid (no parity question)'}.")
        rn = [im["fit"].get("rollNote") for im in c["observation"]["images"] if im.get("fit")]
        if rn and rn[0]:
            L.append(f"  Roll: {rn[0]}.")
    L += ["", "**Fitted pointing against the missions' own pointing** (`pointingChecks`, native pixels):", ""]
    for c in cases:
        items = []
        for im in c["observation"]["images"]:
            for p in im.get("pointingChecks", []):
                tag = "WCS target" if "wcsPixel" in p else "OPUS boresight"
                extra = (f", roll {p['rollDifferenceDeg']:+.2f}° from the WCS" if "rollDifferenceDeg" in p
                         else "")
                items.append(f"{im['product']} {tag} {p['offsetNativePx']:g}{extra}")
        if items:
            L.append(f"* `{c['id']}`: " + "; ".join(items) + ".")
    L += ["", "These offsets are the missions' attitude-knowledge errors plus ours; the fits themselves are tied to "
          "the target's own limb and terminator, which is what the renderer comparison needs.", ""]
    L += ["**App data preview** (disk-integrated ROIs; `photometry.json` alone, no rendering):", ""]
    for c in cases:
        for r in c["rois"]:
            pv = r.get("appDataPreview")
            if not pv:
                continue
            body = next((b for b in c["view"]["bodies"] if b["naifId"] == r.get("target")), None)
            where = (f" (phase {body['phaseDeg']:.1f}°, sub-observer {body['subObserver']['latDeg']:+.1f}° "
                     f"{body['subObserver']['eastLonDeg'] % 360:.1f}° E)" if body else "")
            if "XYZS" in pv and "ratioToExpected" in pv:
                L.append(f"* `{c['id']}` {r['id']}{where}: app/observed Y = {pv['ratioToExpected'][1]:.3f} "
                         f"({pv['deviationInSigma'][1]:+.1f} σ), X {pv['ratioToExpected'][0]:.3f}, "
                         f"Z {pv['ratioToExpected'][2]:.3f}; phase function {pv['labels']['phaseFunction']}.")
            elif "XYZS" in pv:
                L.append(f"* `{c['id']}` {r['id']}: app Y = {pv['XYZS'][1]:.4g} cd/m² (no observed value for this "
                         "ROI).")
            else:
                L.append(f"* `{c['id']}` {r['id']}: {pv['note']}.")
    ledger = json.loads((RAW / "_downloads.json").read_text(encoding="utf-8"))
    L += ["", sizes_line(_du(VALIDATION), ledger, _du(RAW / "validation")), "",
          "**Unit tests** (`pipeline/tests/test_validation.py`): the camera puts the target at the requested pixel "
          "with the pole up; ray casting reproduces a sphere's projected area to 1 % and face-on emission; ring "
          "classes and radii; the pointing fit recovers a synthetic pose to 0.15 px and 2°; grey closure (I/F = 1 "
          "in every band gives exactly the XYZS of sunlight / π d²); band radiance definition; PDS3 label parsing; the "
          "Himawari grid mapping round trip; the companion parity test; and every committed case.json (orthonormal "
          "camera and body matrices, fovY/pitch consistency, reference.bin size, ROI rectangles inside the view, "
          "tolerance = 2σ, fitted target centre = the view's projection of the target).", ""]
    L += ["**Rebuild locks.** Each case's `reproducibility` lock hashes the static import closure of its "
          "build path (the stage fingerprint walker, with the selected instrument reader or Himawari prepare "
          "module), and only the source tables actually read in that build. Shared modules are hashed as "
          "whole files; unrelated stages and their tables are excluded. Raw inputs retain exact byte hashes. "
          "Product dependencies hash canonically serialized consumed fields, including presence, nulls, "
          "labels and source IDs where read: ring profile radii/depths/sources and disk-photometry values/labels. "
          "Unconsumed product method text does not stale a lock; changing a consumed value does. This costs an "
          "explicit field selection at each product read, checked again by the rebuild input capture. "
          "The lock also records the numerical libraries, BLAS/LAPACK configuration, CPU features, PNG "
          "compression, one-thread environment, artifact creation time and exact fit inputs/results. "
          "The pipeline suite checks implementation/tables, environment and present input products offline "
          "without raw images; a missing product is a counted skip. After an applicable code/table/product "
          "change, run `cd pipeline && python -m pipeline.validation renew-locks` with the project Python. "
          "It restarts with BLAS/OMP/MKL threads set to 1, uses each case's recorded SOURCE_DATE_EPOCH and "
          "Earth kernel, and rebuilds from the pinned raw bytes. It refuses the entire batch if any JSON "
          "outside the lock (including regions, expected values, tolerances and fits), reference.bin or "
          "preview.png bytes differ; otherwise it rewrites only the eleven locks. Verification remains "
          "`OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -m pipeline.validation verify`.", ""]
    for c in cases:
        L.append(f"* `{c['id']}`: [`reproducibility`]"
                 f"(../../validation/cases/{c['id']}/case.json).")
    L.append("")
    return "\n".join(L) + "\n"


RUN_REPORT = REPO / "app" / "shots" / "validation" / "report.json"
CONVERGENCE_REPORT = RUN_REPORT.with_name("sampling-convergence.json")
# A different, dated sweep can support a historical comparison, never pretend to be this run.
CONVERGENCE_HISTORY_REPORT = RUN_REPORT.with_name("sampling-history.json")


def recorded_sampling(run: dict) -> int:
    """A report must never assume the sampling of a run (including old runs)."""
    ss = (run.get("options") or {}).get("ss")
    if type(ss) is not int or ss < 1:
        raise ValueError("run must record sampling as a positive integer in options.ss; rerun validation")
    if any(c.get("ss", ss) != ss for c in run.get("cases", []) if not c.get("error")):
        raise ValueError("run must record consistent sampling in options.ss and each case")
    return ss


def sampling_header(run: dict | None) -> str:
    if run is None:
        return "**Rendered sampling:** unknown (no renderer run supplied).\n\n"
    ss = recorded_sampling(run)
    return f"**Rendered sampling:** {ss} × {ss} = {ss * ss} samples per pixel (recorded in the run).\n\n"


def not_rendered(c: dict) -> bool:
    return c.get("status") == "not rendered" or bool(c.get("error"))


def validate_frame_verdicts(run: dict) -> None:
    for c in run.get("cases", []):
        rows = [*c.get("rois", []), *c.get("ratios", [])]
        errors = c.get("errors") or c.get("consoleErrors") or c.get("error")
        if (errors or not_rendered(c)) and any(q.get("pass") is not None for q in rows):
            raise ValueError(f"case {c['id']} carries errors or was not rendered but rows claim verdicts; rerun validation")
        if errors and not not_rendered(c):
            raise ValueError(f"case {c['id']} carries errors without frame validity; rerun validation")
    # Old runners kept GPU errors only at run level: they cannot attribute those verdicts safely.
    if run.get("consoleErrors") and not any(c.get("consoleErrors") or c.get("errors") for c in run.get("cases", [])):
        raise ValueError("run carries unattributed errors but rows may claim verdicts; rerun validation")


def _sampling_rows(run: dict) -> list[tuple]:
    validate_frame_verdicts(run)
    rows = []
    for c in run["cases"]:
        for q in c.get("rois", []):
            rows.append((c["id"], q["id"], q["rendered"]["mean"], q["pass"], q["failing"], not_rendered(c)))
        for q in c.get("ratios", []):
            rows.append((c["id"], f"{q['numerator']} / {q['denominator']}", q["rendered"], q["pass"], q["failing"], not_rendered(c)))
    return rows


def convergence_section(run: dict, path=None) -> str:
    """Optional sweep evidence from scripts/validate-sampling.mjs; refuse stale/mismatched evidence."""
    path = CONVERGENCE_REPORT if path is None else path
    if not path.exists():
        return ""
    sweep = json.loads(path.read_text(encoding="utf-8"))
    runs = sweep.get("runs", [])
    if sweep.get("schema") != "validation-sampling-v1" or [recorded_sampling(r) for r in runs] != [1, 2, 3, 4, 6]:
        raise ValueError("sampling convergence must record the 1, 2, 3, 4, 6 grids")
    if run not in runs:
        raise ValueError("sampling convergence must contain the same run being reported; rerun the sweep or remove its file")
    identity = lambda r: (r.get("git"), r.get("dataGeneratedAt"), r.get("gpu"), r.get("dataMissing"),
                          {k: v for k, v in r["options"].items() if k != "ss"},
                          [c["id"] for c in r["cases"]])
    if any(identity(r) != identity(run) for r in runs):
        raise ValueError("sampling convergence inputs, adapter or options differ between grids")
    for c in run["cases"]:
        formats = {cc.get("hdrFormat") for r in runs for cc in r["cases"] if cc["id"] == c["id"] and not not_rendered(cc)}
        if len(formats) > 1:
            raise ValueError("sampling convergence HDR formats differ between valid frames")
    rows = [_sampling_rows(r) for r in runs]
    if any([(q[0], q[1]) for q in rr] != [(q[0], q[1]) for q in rows[0]] for rr in rows):
        raise ValueError("sampling convergence region sets differ between grids")
    columns = " | ".join(f"{r['options']['ss']} × {r['options']['ss']}" for r in runs)
    L = ["### Sampling convergence", "",
         f"Sweep of {runs[0]['generatedAt']} through {runs[-1]['generatedAt']} (git {run.get('git')}, "
         f"data {run.get('dataGeneratedAt')}){rendered_by(run)}. "
         "Source: `app/shots/validation/sampling-convergence.json` (`cd app && node scripts/validate-sampling.mjs`).",
         "", "Every ROI and ratio, all channels. ROI X/Y/Z: cd/m²; S: scotopic cd/m²; ratios: dimensionless. "
         "Δ 4→6 = 100 × (value at 4 / value at 6 − 1); zero/zero is 0%, nonzero/zero is unknown. "
         "These finite grids show convergence evidence, not a proof. Choose the coarsest stable grid by the values "
         "and every verdict; a stable tally alone is insufficient. No law, source or tolerance is selected here.", "",
         f"| case | region | channel | {columns} | Δ 4→6 |", "|---|---|---|---|---|---|---|---|---|"]
    for i, q in enumerate(rows[0]):
        for k, ch in enumerate(CH):
            values = [rr[i][2][k] if rr[i][2] and not rr[i][5] else None for rr in rows]
            a, b = values[3], values[4]
            delta = None if a is None or b is None or not math.isfinite(a) or not math.isfinite(b) else (100 * (a / b - 1) if b else (0 if a == 0 else None))
            ds = "—" if delta is None else f"{'+' if delta >= 0 else ''}{_g(delta, 6)} %"
            L.append(f"| `{q[0]}` | {q[1]} | {ch} | " + " | ".join("not rendered" if rows[j][i][5] else _g(v, 7) for j, v in enumerate(values)) + f" | {ds} |")
    L += ["", f"| case | region | {columns} |", "|---|---|---|---|---|---|---|"]
    for i, q in enumerate(rows[0]):
        verdicts = ["not rendered" if rr[i][5] else "not compared" if rr[i][3] is None else "pass" if rr[i][3] else f"fail ({''.join(rr[i][4])})" for rr in rows]
        L.append(f"| `{q[0]}` | {q[1]} | " + " | ".join(verdicts) + " |")
    L += ["", "Invalid frames contribute no convergence statistics or verdict changes.", "",
          "| sampling | case | finest valid sampling | largest relative difference (%) |", "|---|---|---|---|"]
    level_max = []
    for j, r in enumerate(runs):
        maxima = []
        for c in r["cases"]:
            indices = [i for i, q in enumerate(rows[j]) if q[0] == c["id"]]
            valid = [k for k, rr in enumerate(rows) if any(q[0] == c["id"] and not q[5] for q in rr)]
            ref = max(valid, key=lambda k: runs[k]["options"]["ss"]) if valid else None
            differences = []
            if not not_rendered(c) and ref is not None:
                for i in indices:
                    for a, b in zip(rows[j][i][2] or [], rows[ref][i][2] or []):
                        if a is not None and b is not None and math.isfinite(a) and math.isfinite(b) and (b or a == 0):
                            differences.append(abs(100 * (a / b - 1)) if b else 0)
            largest = max(differences) if differences else None
            if largest is not None:
                maxima.append(largest)
            value = "not rendered" if not_rendered(c) else _g(largest, 7) + " %"
            finest = runs[ref]["options"]["ss"] if ref is not None else "—"
            L.append(f"| {r['options']['ss']} × {r['options']['ss']} | `{c['id']}` | {finest} | {value} |")
        level_max.append(max(maxima) if maxima else None)
    L += ["", "| sampling | pass | fail | not rendered | largest relative difference (%) |", "|---|---|---|---|---|"]
    for j, r in enumerate(runs):
        qs = [(c, q) for c in r["cases"] for q in [*c.get("rois", []), *c.get("ratios", [])]]
        passes = sum(not not_rendered(c) and q["pass"] is True for c, q in qs)
        fails = sum(not not_rendered(c) and q["pass"] is False for c, q in qs)
        invalid = sum(not_rendered(c) for c, q in qs)
        L.append(f"| {r['options']['ss']} × {r['options']['ss']} | {passes} | {fails} | {invalid} | {_g(level_max[j], 7)} % |")
    default_index = next(j for j, r in enumerate(runs) if r == run)
    L += ["", f"Reported default {run['options']['ss']} × {run['options']['ss']}: largest relative difference "
          f"{_g(level_max[default_index], 7)} % against each case's finest valid level. These run values supply "
          "the numerical justification; a case whose finest valid level is the default has no finer check."]
    changes = [f"{q[0]} / {q[1]}" for i, q in enumerate(rows[0])
               if len({rr[i][3] for rr in rows if not rr[i][5] and rr[i][3] is not None}) > 1]
    L += ["", "Verdict depends on sampling: " + ("; ".join(changes) or "none") + " (valid frames only)."]
    return "\n".join(L) + "\n\n"



def _g(v, d=4):
    return "—" if v is None or not math.isfinite(v) else f"{v:.{d}g}"


def rendered_by(run: dict) -> str:
    """Which WebGPU adapter rendered the run and on what machine, when the runner recorded them (scripts/validate.mjs
    `gpu` and `host`; runs before that option were SwiftShader and say nothing)."""
    gpu, host = run.get("gpu"), run.get("host")
    if not gpu:
        return ""
    a = gpu.get("adapter") or {}
    name = " ".join(x for x in (a.get("vendor"), a.get("architecture")) if x) or "unnamed adapter"
    kind = {"swiftshader": "SwiftShader (software WebGPU)", "hardware": "the machine's GPU"}.get(gpu.get("mode"),
                                                                                                 str(gpu.get("mode")))
    where = f", on {host['cpu']} ({host['threads']} threads)" if host and host.get("cpu") else ""
    return f", rendered by {kind}, adapter `{name}`{where}"


def tally_lines(run: dict) -> str:
    """Count verdicts by row type; a ratio is never silently counted as a region."""
    regions = [(c, q) for c in run["cases"] for q in c.get("rois", [])]
    ratios = [(c, q) for c in run["cases"] for q in c.get("ratios", [])]

    def counts(rows):
        return (sum(not not_rendered(c) and q["pass"] is True for c, q in rows),
                sum(not not_rendered(c) and q["pass"] is False for c, q in rows),
                sum(not_rendered(c) for c, q in rows),
                sum(not not_rendered(c) and q["pass"] is None for c, q in rows))

    def line(name, rows):
        yes, no, invalid, uncompared = counts(rows)
        return f"**{name}: {yes} pass, {no} fail, {invalid} not rendered, {uncompared} not compared.**"

    brightness = [(c, q) for c, q in regions if q["expectedType"] == "value"]
    sky = [(c, q) for c, q in regions if q["expectedType"] == "upper-limit"]
    return "\n\n".join((line("Regions", regions), line("Brightness regions", brightness),
                          line("Sky upper limits", sky), line("Ratio rows", ratios)))


def run_findings(run: dict) -> str:
    """Only this run supplies the failure rows and their numerical descriptions."""
    validate_frame_verdicts(run)
    groups = {}
    region_count = ratio_count = 0
    for c in run["cases"]:
        if not_rendered(c):
            continue
        for is_ratio, qs in ((False, c.get("rois", [])), (True, c.get("ratios", []))):
            for q in qs:
                if q["pass"] is not False:
                    continue
                ratio_count += int(is_ratio)
                region_count += int(not is_ratio)
                if is_ratio:
                    group = "Ratio rows"
                elif q.get("target") in (501, 502, 503, 504):
                    group = "Galilean moons"
                elif c["id"].startswith("earth-"):
                    group = "Earth"
                elif c["id"].startswith("saturn-"):
                    group = "Saturn rings" if q.get("kind") == "ring" else "Saturn globe"
                else:
                    group = c["id"]
                groups.setdefault(group, []).append((c, q, is_ratio))
    L = ["**What the failures say.**", "", "### Findings computed from this run", "",
         f"{region_count + ratio_count} failing rows: {region_count} region{'s' if region_count != 1 else ''} "
         f"and {ratio_count} ratio row{'s' if ratio_count != 1 else ''} "
         "(valid frames only). Each row below names a failing channel; relative error and tolerance "
         "are percentages of the expected value. ROI radiance is in cd/m² (S: scotopic cd/m²); "
         "ratios are dimensionless.", ""]
    if not groups:
        L += ["No failing rows in valid frames.", ""]
    for group, rows in groups.items():
        L += [f"#### {group}", "",
              "| case | row | channel | expected ± tolerance | rendered | relative error (%) | tolerance (%) | σ |",
              "|---|---|---|---|---|---|---|---|"]
        for c, q, is_ratio in rows:
            name = f"{q['numerator']} / {q['denominator']}" if is_ratio else q["id"]
            rendered = q["rendered"] if is_ratio else q["rendered"]["mean"]
            for channel in q["failing"]:
                k = CH.index(channel)
                value = rendered[k]
                if not is_ratio and q["expectedType"] == "upper-limit":
                    expected, error, tolerance, dev = f"≤ {_g(q['upperLimit'][k], 5)}", None, None, None
                else:
                    e, t = q["expected"][k], q["tolerance"][k]
                    expected = f"{_g(e, 5)} ± {_g(t, 3)}"
                    error = 100 * (value / e - 1) if e else None
                    tolerance = 100 * t / abs(e) if e else None
                    sigma = t / TOLERANCE_K if is_ratio else q["sigma"][k]
                    dev = (value - e) / sigma if sigma else None
                err = "—" if error is None else f"{error:+.2f}"
                deviation = "—" if dev is None else f"{dev:+.2f}"
                L.append(f"| `{c['id']}` | {name} | {channel} | {expected} | {_g(value, 5)} | "
                         f"{err} | {'—' if tolerance is None else f'{tolerance:.1f}'} | {deviation} |")
        L.append("")
    return "\n".join(L) + "\n"


def sampling_history_section(run: dict, path=None) -> str:
    """An optional independent sweep is explicitly history, with its own commit and date.

    Use the same validity/identity rules as current-run convergence. Old sweeps with unattributed
    errors are refused; an audited migration must attribute them and clear invalid verdicts first.
    """
    path = CONVERGENCE_HISTORY_REPORT if path is None else path
    if not path.exists():
        return ""
    sweep = json.loads(path.read_text(encoding="utf-8"))
    runs = sweep.get("runs", [])
    if not runs:
        raise ValueError("sampling history must contain runs")
    # Validate the full sweep, without claiming it includes the current renderer run.
    convergence_section(runs[0], path)
    rows = [_sampling_rows(r) for r in runs]
    L = ["### History: sampling sweep", "",
         f"Measured {runs[0]['generatedAt']} through {runs[-1]['generatedAt']} at git "
         f"`{runs[0].get('git')}`, data {runs[0].get('dataGeneratedAt')}{rendered_by(runs[0])}. "
         "Source: `app/shots/validation/sampling-history.json`. This is a separate historical sweep, "
         "not measurements of the run above.", ""]
    if sweep.get("frameValidityAudit"):
        L += ["Frame-validity audit: " + sweep["frameValidityAudit"], ""]
    L += ["Largest absolute relative difference over all ROI and ratio channels, against each case's "
          "finest valid level. Invalid frames contribute no measurements. Zero/zero contributes zero; "
          "nonzero/zero has no relative difference.", "",
          "| sampling | largest relative difference (%) | not rendered cases |",
          "|---|---|---|"]
    maxima = []
    for j, r in enumerate(runs):
        differences = []
        for i, q in enumerate(rows[j]):
            if q[5]:
                continue
            valid = [k for k, rr in enumerate(rows) if not rr[i][5]]
            ref = max(valid, key=lambda k: recorded_sampling(runs[k]))
            for a, b in zip(q[2] or [], rows[ref][i][2] or []):
                if a is not None and b is not None and math.isfinite(a) and math.isfinite(b) and (b or a == 0):
                    differences.append(abs(100 * (a / b - 1)) if b else 0)
        largest = max(differences) if differences else None
        maxima.append(largest)
        ss = recorded_sampling(r)
        invalid = ", ".join(f"`{c['id']}`" for c in r["cases"] if not_rendered(c)) or "none"
        L.append(f"| {ss} × {ss} | {_g(largest, 6)} | {invalid} |")
    for c in runs[0]["cases"]:
        valid = [r for r in runs if not not_rendered(next(cc for cc in r["cases"] if cc["id"] == c["id"]))]
        if valid and len(valid) < len(runs):
            finest = max(recorded_sampling(r) for r in valid)
            L += ["", f"`{c['id']}`: finest valid level is {finest} × {finest}; it has no finer valid check."]
    ss = recorded_sampling(run)
    ix = next((j for j, r in enumerate(runs) if recorded_sampling(r) == ss), None)
    L += ["", f"Current run sampling {ss} × {ss}: " +
          (f"the historical sweep's matching level differs by at most {_g(maxima[ix], 6)} % from each "
           "case's finest valid level. The default remains provisional, with the missing finer "
           "checks stated above; finite grids do not establish the coarsest converged grid."
           if ix is not None else "no matching level in this historical sweep.")]
    return "\n".join(L) + "\n\n"


def run_section(run: dict, interpretation: str) -> str:
    """§7: the renderer's run (`npm run validate`, app/shots/validation/report.json): Y per ROI and the verdicts."""
    recorded_sampling(run)
    validate_frame_verdicts(run)
    o = run["options"]
    cmd = f"cd app && npm run validate -- --ss {o['ss']}" + (
        " --gpu hardware" if (run.get("gpu") or {}).get("mode") == "hardware" else "")
    L = ["## 7. The renderer against the cases\n",
         f"Run of {run['generatedAt'][:16].replace('T', ' ')} UTC (git {run.get('git')}, data built "
         f"{(run.get('dataGeneratedAt') or '?')[:16].replace('T', ' ')}), reality level {o['reality']}, "
         f"{o['ss']} × {o['ss']} samples per pixel{rendered_by(run)}: `{cmd}` (the full table, with X, Z, S, is in "
         "`app/shots/validation/report.md`). Y in cd/m²; the verdict covers X, Y, Z and S (failing channels named).",
         "", "| case | ROI | expected Y ± 2σ | rendered Y | rendered / expected | σ | verdict |", "|---|---|---|---|---|---|---|"]
    for c in run["cases"]:
        if c.get("error") and not c.get("rois"):
            L.append(f"| `{c['id']}` | — | — | — | — | — | did not render: {c['error'][:120]} |")
            continue
        for q in c["rois"]:
            if not_rendered(c):
                reason = (q.get("reason") or c.get("reason") or c.get("error") or "invalid frame").replace("|", "/").replace("\n", " ")
                L.append(f"| `{c['id']}` | {q['id']} | — | — | — | — | not rendered: {reason} |")
                continue
            if q["expectedType"] == "value":
                exp = f"{_g(q['expected'][1])} ± {_g(q['tolerance'][1], 2)}"
                ratio, dev = f"{q['ratio'][1]:.3f}", f"{q['deviationSigma'][1]:+.1f}"
            elif q["expectedType"] == "upper-limit":
                exp, ratio, dev = f"≤ {_g(q['upperLimit'][1])}", "—", "—"
            else:
                exp, ratio, dev = "—", "—", "—"
            v = {True: "pass", False: f"**fail** ({''.join(q['failing'])})", None: "not compared"}[q["pass"]]
            L.append(f"| `{c['id']}` | {q['id']} | {exp} | {_g(q['rendered']['mean'][1])} | {ratio} | {dev} | {v} |")
        for r in c.get("ratios", []):
            if not_rendered(c):
                reason = (r.get("reason") or c.get("reason") or c.get("error") or "invalid frame").replace("|", "/").replace("\n", " ")
                L.append(f"| `{c['id']}` | {r['numerator']} / {r['denominator']} | — | — | — | — | not rendered: {reason} |")
                continue
            v = {True: "pass", False: f"**fail** ({''.join(r['failing'])})", None: "not compared"}[r["pass"]]
            L.append(f"| `{c['id']}` | {r['numerator']} / {r['denominator']} | {_g(r['expected'][1])} ± "
                     f"{_g(r['tolerance'][1], 2)} | {_g(r['rendered'][1]) if r['rendered'] else '—'} | — | — | {v} |")
    L += ["", tally_lines(run) + "\n\nHow each body was drawn:", ""]
    for c in run["cases"]:
        if not_rendered(c):
            continue
        bodies = "; ".join(f"{b['name']}: {', '.join(b.get('uses') or []) or b['drawn']}" for b in c["scene"]["bodies"])
        warn = "; ".join(c.get("stats", {}).get("warnings") or [])
        L.append(f"* `{c['id']}`: {bodies}." + (f" Renderer warnings: {warn}." if warn else ""))
    return "\n".join(L) + "\n\n" + run_findings(run) + interpretation


def write(extra_sections: str = "", run: dict | None = None, run_interpretation: str = "") -> None:
    if run is not None:
        validate_frame_verdicts(run)
    sampling = sampling_header(run)  # validate before reading inputs or replacing the report
    convergence = (convergence_section(run) + sampling_history_section(run)) if run is not None else ""
    cases = [json.loads(p.read_text(encoding="utf-8")) for p in sorted((VALIDATION / "cases").glob("*/case.json"))]
    parts = [HEADER.replace("\n\n", "\n\n" + sampling, 1), "## 4. The cases\n\n", summary_table(cases), "\n",
             "Sizes: `validation/` holds only case.json, reference.bin (float32 I/F on the view grid) and "
             "preview.png per case; the downloaded images are fetched into `data/raw/validation/` (git-ignored) "
             "and may be deleted after the build (`clean`).\n\n"]
    for c in cases:
        parts.append(case_section(c) + "\n")
    parts.append(findings(cases))
    parts.append(extra_sections)
    if run is not None:
        parts.append("\n" + run_section(run, run_interpretation))
        parts.append("\n" + convergence)
    # Sections supply internal separators; only the writer normalizes the file's final newline.
    REPORT.write_text("".join(parts).rstrip() + "\n", encoding="utf-8", newline="\n")


FINDINGS = """## 6. Limitations and open issues

1. **Pointing is fitted, not taken from C-kernels.** The fitted camera is tied to the target itself (limb,
   terminator, rings); the mission pointing serves as a check (§5) and, where the image cannot decide,
   for the parity (Voyager: a Saturn frame with moons; LORRI: the header WCS, which also gives the roll).
2. **Scene changes with time are not in the tolerance.** Earth's clouds, giant-planet cloud features,
   Io's volcanic deposits and seasonal changes can differ from the observation. `cloudTimeOffsetH`
   records the Himawari regions' timing relative to the cloud overpass. Texture in a region contributes
   to the noise term but does not cover a systematically different scene.
3. **Single-band cases (LORRI)** give XYZS only through the body's disk-integrated spectral shape
   ('estimated'). Regional colour differences can exceed the grey-versus-shape spectral term.
   The band radiance itself is 'derived' and is the sharper quantity.
4. **Instrument responses:** the Voyager filter curves are the pre-launch curves digitized from Smith
   et al. (1977), generic to both spacecraft; the EPOXI calibration notes in each case describe the
   HRI-VIS red leaks; the LORRI response is the SVO copy of the archive's launch calibration.
5. **LORRI calibration:** the reader uses the in-flight RSOLAR from Weaver et al. (2020), including
   for the Jupiter-encounter frames. The case's calibration notes record both it and the archived keyword.
6. **Not in this set:** Mars, Mercury, a high-resolution lunar case, Titan and Venus.
7. **Himawari:** an equatorial segment, without a disk-integrated ROI. The app's Earth albedo comes
   from a different Himawari scene; each case records its spectral convention.
8. **Sky ROIs** are upper limits: the camera's scattered light and zero level are included in them.
9. **Sampling:** the reference is an area average per pixel. Sampling only pixel centres can miss
   within-pixel variation, which the registration term does not include for the renderer.
10. **App data previews (§5)** evaluate the data without rendering, as built with the cases. The Moon's
    preview uses ROLO's Earth-based near-side photometry, while EPOXI saw the far side. The renderer
    uses the lunar maps at ROLO's reference geometry. The Galilean previews are longitude-averaged;
    the renderer also uses the measured rotational variation (`rotation-slices-v1`). A preview is not
    a rendered measurement.
"""

RUN_FINDINGS = """### Current reading (decisions of 2026-10-07)

* **Galilean moons:** the disk totals have a common deficit; no factor is applied. Their maps also
  carry hemispheric gradients: the large-scale term is estimated. The leading/trailing comparison
  with measured rotation slices identifies a disagreement for Ganymede and Callisto. These rows
  do not separate every map contribution from the spatial law.
* **Earth:** clouds without a thickness retrieval use an estimated population statistic. A design
  for that term is under way. Cloud timing and a different scene limit what these rows establish.
* **Jupiter's centre:** the app uses a 2025 map against a 2007 planet. This is a scene difference,
  outside the case's uncertainty budget, rather than evidence for choosing a different law.
* **Saturn's terminator:** the frame shows night-side light with ringshine's signature, which the
  app does not draw. The deficit does not establish that the Barkstrom law darkens too steeply.
  **Ring rows:** the case's phase is beyond the product's calibrated 0.25–47° domain;
  [published measurements beyond 47° exist](../sources/rings-high-phase.md) and are not yet included. Ring brightness
  is shown as unknown, and these HDR rows compare the reference with zero ring light.
* **Moon/Earth ratio:** the table above gives its refreshed tolerance, failing channels and relative
  errors. It depends on the Earth's rendered clouds and on a scene from another epoch. It is not
  an independent test of the Moon's scale.
* **Passes have limits:** sky upper limits test leakage beyond bodies, with no sky loaded; they
  cannot fail because a sky model is too bright. Pluto's map and law use the same flyby as the
  case, so those rows test the app against its own inputs; only its albedo is independent.
  Saturn's limb is outside the map's polar coverage, and Uranus's view is outside its map.
  Jupiter's disk total and the broad single-band spectral budgets do not establish that the
  spatial pattern or spectral convention is correct.

These readings follow the validation triage's findings, not a fit of any case, tolerance or model.
"""
